nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000'] # React ou autre origine frontend
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': # Appliquer les règles pour toutes les routes
            allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000']
